FROM maven:3.8.8-eclipse-temurin-8

WORKDIR /workspace

COPY pom.xml /workspace/pom.xml
COPY ruoyi-admin/pom.xml /workspace/ruoyi-admin/pom.xml
COPY ruoyi-common/pom.xml /workspace/ruoyi-common/pom.xml
COPY ruoyi-framework/pom.xml /workspace/ruoyi-framework/pom.xml
COPY ruoyi-generator/pom.xml /workspace/ruoyi-generator/pom.xml
COPY ruoyi-quartz/pom.xml /workspace/ruoyi-quartz/pom.xml
COPY ruoyi-system/pom.xml /workspace/ruoyi-system/pom.xml

EXPOSE 8080
ENV JAVA_OPTS=""
ENV SPRING_PROFILES_ACTIVE=docker

COPY startup.sh /workspace/startup.sh
RUN chmod +x /workspace/startup.sh

CMD ["bash", "/workspace/startup.sh"]
